[general]

import = ["~/.config/alacritty/dracula.toml"]


[window]

padding = { x = 0, y = 0 }
dynamic_padding = true
startup_mode = "Maximized"
dynamic_title = false
opacity = 0.7
blur = true


[cursor]

style = { shape = "Block", blinking = "Always" }
blink_timeout = 60


[mouse]

hide_when_typing = true


[font]

normal = { family = "0xProto Nerd Font Mono", style = "Regular" }
size = 14
