import = ["~/.config/alacritty/dracula.toml"]


[window]

padding = { x = 0, y = 0 }
dynamic_padding = true
startup_mode = "Maximized"
dynamic_title = false


[font]

normal = { family = "0xProto Nerd Font Mono", style = "Regular" }
size = 14
